### ISSUE TITLE
Can not export SPDX 2.3 to Excel formats

### ISSUE THREAD

**Issue by tienlee** [spdx/spdx-java-spreadsheet-store#17]
Hello @goneall 

I am using the tools-java library for sw360 and implementing an export function to support SPDX 2.3
I can't export SPDX 2.3 to xls/xlsx by using this library (spdx-java-spreadsheet-store), I can fix this issue and will create a pull request now.

Please help me check this PR.

**Comment by tienlee** [comment]
The PR was merged, thanks @goneall 

Could you please tag this library and update/tag the tools-java library?

**Comment by goneall** [comment]
This is now tagged as `v1.1.3` and released.
